<?php

namespace AppBundle\Repository;

/**
 * BookImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookImageRepository extends \Doctrine\ORM\EntityRepository
{

}
