<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{

    function getBookAndDealImages($bookId){

        return $this->getEntityManager()
            ->createQueryBuilder('b')
            ->select('b.bookImage ,bdi.imageUrl')

            ->from('AppBundle:Book', 'b')
            ->innerJoin('AppBundle:BookDeal', 'bd', 'WITH', 'b.id = bd.book')
            ->innerJoin('AppBundle:BookDealImage', 'bdi', 'WITH', 'bd.id = bdi.bookDeal')
            ->andwhere('b.id = :bookId')

            ->andwhere('bd.bookStatus = ' . "'Activated'")
            ->andwhere('bd.bookSellingStatus = ' . "'Selling'")
            ->setParameter('bookId', $bookId)
            ->getQuery()
            ->getResult();

    }

    function findCustomBook($keyword){
        return $this->getEntityManager()
            ->createQueryBuilder('b')
            ->select('b.bookTitle,
                     b.bookDirectorAuthorArtist,
                     b.bookEdition,
                     b.bookPublisher,
                     b.bookPublishDate,
                     b.bookBinding,
                     b.bookPage,
                     b.bookLanguage,
                     b.bookDescription,
                     b.bookIsbn10,
                     b.bookIsbn13,
                     b.bookImage,
                     b.bookAmazonPrice
                     ')

            ->from('AppBundle:Book', 'b')

            ->andwhere('b.bookTitle LIKE :keyword OR
                        b.bookIsbn10 LIKE :keyword OR
                        b.bookIsbn13 LIKE :keyword OR
                        b.bookDirectorAuthorArtist LIKE :keyword
                        ')



            ->setParameter('keyword', "%".$keyword."%")
            ->getQuery()
            ->getResult();
    }

    function findCustomBookByIsbn($isbn){
        return $this->getEntityManager()
            ->createQueryBuilder('b')
            ->select('b.bookTitle,
                     b.bookDirectorAuthorArtist,
                     b.bookEdition,
                     b.bookPublisher,
                     b.bookPublishDate,
                     b.bookBinding,
                     b.bookPage,
                     b.bookLanguage,
                     b.bookDescription,
                     b.bookIsbn10,
                     b.bookIsbn13,
                     b.bookImage,
                     b.bookAmazonPrice
                     ')

            ->from('AppBundle:Book', 'b')

            ->andwhere('b.bookIsbn10 LIKE :isbn')



            ->setParameter('isbn', $isbn)
            ->getQuery()
            ->getResult();
    }
}
