<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    function alreadyContacted($data,$userId){
        $result = $this->getEntityManager()
            ->createQueryBuilder('c')
            ->select('c.id')

            ->from('AppBundle:Contact', 'c')
            ->andwhere('c.buyer = :userId')
            ->andwhere('c.bookDeal = :bookDeal')
            ->setParameter('userId', $userId)
            ->setParameter('bookDeal', $data['bookDeal'])
            ->getQuery()->getResult();
        if(count($result)>0){
            return true;
        }else{
            return false;
        }

    }
}
