<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{

    public function getLogSearchResult($usernameQuery,$logTypeQuery,$logUserTypeQuery, $pageNumber, $pageSize,$sort){
        $firstResult = ($pageNumber - 1) * $pageSize;
        $qb= $this->getEntityManager()
            ->createQueryBuilder('u')
            ->select('l.id as logId, u.username,l.logType,l.logDateTime,l.logUserType,l.logDescription,l.userIpAddress')
            ->from('AppBundle:Log', 'l')
            ->innerJoin('AppBundle:User', 'u', 'WITH', 'u.id = l.user')

            ->andwhere('u.username LIKE :usernameQuery ')
            ->andwhere('l.logType LIKE :logTypeQuery')
            ->andwhere('l.logUserType LIKE :logUserTypeQuery')



            ->setParameter('usernameQuery', '%' . $usernameQuery . '%')
            ->setParameter('logTypeQuery', '%' . $logTypeQuery . '%')
            ->setParameter('logUserTypeQuery', '%' . $logUserTypeQuery. '%')


            ->setMaxResults($pageSize)
            ->setFirstResult($firstResult);


        foreach($sort as  $key => $value){
            $qb->addOrderBy("l.".$key,$value);
        }
        return $qb->getQuery()
            ->getResult();
    }

    public function getLogSearchNumber($usernameQuery,$logTypeQuery,$logUserTypeQuery){
        $qb =  $this->getEntityManager()->createQueryBuilder('l')
            ->select('COUNT(l)')
            ->from('AppBundle:Log', 'l')
            ->innerJoin('AppBundle:User', 'u', 'WITH', 'u.id = l.user')

            ->andwhere('u.username LIKE :usernameQuery ')
            ->andwhere('l.logType LIKE :logTypeQuery')
            ->andwhere('l.logUserType LIKE :logUserTypeQuery')

            ->setParameter('usernameQuery', '%' . $usernameQuery . '%')
            ->setParameter('logTypeQuery', '%' . $logTypeQuery . '%')
            ->setParameter('logUserTypeQuery', '%' . $logUserTypeQuery. '%');


        return $qb->getQuery()
            ->getSingleScalarResult();
    }

    public function getUsersLog($startDate, $endDate, $logType)
    {
        $sql = "SELECT COUNT(id) as count,date_format(log_date_time,'%d-%b-%Y') as logDate,log_type FROM `logs` WHERE (log_type='" . $logType . "' ) and (log_date_time BETWEEN '" . $startDate . "' AND '" . $endDate . "') GROUP by date_format(log_date_time,'%y-%m-%d'),log_type";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
