<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    function getAllNewsSearchResult($searchQuery, $pageNumber, $pageSize,$sort){

        $firstResult = ($pageNumber - 1) * $pageSize;
        $qb= $this->getEntityManager()
            ->createQueryBuilder('n')
            ->select('n.id as newsId,
                      n.newsTitle,
                      n.newsDescription,
                      n.newsStatus,
                      n.newsDateTime,
                      n.newsType,
                      n.newsVideoEmbedCode
            ')
            ->from('AppBundle:News', 'n')
            ->andwhere('n.newsTitle LIKE :query ')
            ->setParameter('query', '%' . $searchQuery . '%')
            ->setMaxResults($pageSize)
            ->setFirstResult($firstResult);

        foreach($sort as  $key => $value){
            $qb->addOrderBy("n.".$key,$value);
        }
        return $qb->getQuery()
            ->getResult();

    }


    public function getAllNewsSearchNumber($searchQuery)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('n')
            ->select('COUNT(n)')
            ->from('AppBundle:News', 'n')
            ->andwhere('n.newsTitle LIKE :query ')
            ->setParameter('query', '%' . $searchQuery . '%')
            ->getQuery()
            ->getSingleScalarResult();
    }


    function getAllActiveNewsSearchResult($searchQuery, $pageNumber, $pageSize,$sort){

        $firstResult = ($pageNumber - 1) * $pageSize;
        $qb= $this->getEntityManager()
            ->createQueryBuilder('n')
            ->select('n.id as newsId,
                      n.newsTitle,
                      n.newsDescription,
                      n.newsStatus,
                      n.newsDateTime,
                      n.newsType,
                      n.newsVideoEmbedCode
            ')
            ->from('AppBundle:News', 'n')
            ->andwhere('n.newsTitle LIKE :query ')
            ->andwhere('n.newsStatus='."'Activated'")
            ->orderBy('n.newsDateTime','DESC')
            ->setParameter('query', '%' . $searchQuery . '%')
            ->setMaxResults($pageSize)
            ->setFirstResult($firstResult);

        foreach($sort as  $key => $value){
            $qb->addOrderBy("n.".$key,$value);
        }
        return $qb->getQuery()
            ->getResult();

    }


    public function getAllActiveNewsSearchNumber($searchQuery)
    {
        return $this->getEntityManager()
            ->createQueryBuilder('n')
            ->select('COUNT(n)')
            ->from('AppBundle:News', 'n')
            ->andwhere('n.newsTitle LIKE :query ')
            ->andwhere('n.newsStatus='."'Activated'")
            ->setParameter('query', '%' . $searchQuery . '%')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
