<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StarRepository extends EntityRepository
{
    function checkIfAlreadyAddedToStarList($userId,$bookDealId){

            $data =  $this->getEntityManager()
                ->createQueryBuilder('s')
                ->select('s.id')

                ->from('AppBundle:Star', 's')
                ->andwhere('s.user = :user')
                ->andwhere('s.bookDeal = :bookDeal')

                ->setParameter('bookDeal', $bookDealId)
                ->setParameter('user', $userId)
                ->getQuery()
                ->getResult();

            if(count($data)>0){
                return true;
            }else{
                return false;
            }

    }
}
