<?php

namespace AppBundle\Repository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCountryId($countryId){
        return $this->getEntityManager()
            ->createQueryBuilder('s')
            ->select('s.id,s.stateName, s.stateShortName')
            ->from('AppBundle:State', 's')
            ->andwhere('s.country = :countryId')
            ->setParameter('countryId', $countryId)
            ->getQuery()
            ->getResult();
    }
}
