<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishListRepository extends EntityRepository
{
    function checkIfAlreadyAddedToWishList($userId,$bookId){
       $data =  $this->getEntityManager()
            ->createQueryBuilder('w')
            ->select('w')

            ->from('AppBundle:WishList', 'w')
            ->andwhere('w.user = :user')
            ->andwhere('w.book = :book')

            ->setParameter('book', $bookId)
            ->setParameter('user', $userId)
            ->getQuery()
            ->getResult();


        if(count($data)>0){
            return $data[0];
        }else{
            return false;

        }
    }

    function removeWishListItem($id){

    }

    function checkIfBookAlreadyAddedByIsbn($userId,$isbn){
        $data =  $this->getEntityManager()
            ->createQueryBuilder('q')
            ->select('w.id')

            ->from('AppBundle:WishList', 'w')
            ->innerJoin('AppBundle:Book', 'b', 'WITH', 'b.id = w.book')
            ->andwhere('w.user = :user')
            ->andwhere('b.bookIsbn10 = :bookIsbn')

            ->setParameter('bookIsbn', $isbn)
            ->setParameter('user', $userId)
            ->getQuery()
            ->getResult();

        if(count($data)>0){
            return true;

        }else{
            return false;

        }
    }
}
