AppBundle\Entity\News:
    type: entity
    table: news
    repositoryClass: AppBundle\Repository\NewsRepository

    oneToMany:
        newsImages:
            targetEntity: NewsImage
            mappedBy: news
            cascade: [persist,remove]

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        newsTitle:
            type: text
        newsDescription:
            type: text
        newsDateTime:
            type: datetime
        newsType:
            type: string
            length: '20'
            options:
                default: 'imageType'
        newsVideoEmbedCode:
            type: text
            nullable: true
        newsStatus:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
