AppBundle\Entity\RefreshToken:
    type: entity
    table: refresh_token

    manyToOne:
        client:
          targetEntity: Client

          joinColumn:
            nullable: false

        user:
          targetEntity: User

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO


    lifecycleCallbacks: {  }
